# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_starter_development

  # The specified database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  # username: rails_starter

  # The password associated with the postgres role (username).
  # password:

  # Connect on a TCP socket. Omitted the default port since PostgreSQL uses
  # the default port (5432) unless otherwise specified.
  # host: localhost

  # The TCP port the server listens on. Default: 5432
  # If your server runs on a different port number, change accordingly.
  # port: 5432

  # Schema search path. The server defaults to $user,public
  # schema_search_path: myapp,sharedapp,public

  # Minimum log levels in PostgreSQL. Valid values are DEBUG5, DEBUG4,
  # DEBUG3, DEBUG2, DEBUG1, LOG, NOTICE, WARNING, ERROR, LOG, FATAL, and PANIC
  # The default is NOTICE
  # min_messages: NOTICE

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: rails_starter_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a environment variable (ENV) when booting
# the application. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values in this file. Alternatively, you can specify a connection URL
# here instead of a host, database, username and password.
#
# Example:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
